application:
  name: musee-lookout
  port: 8000
  healthPath: /api/health

modules:
  task:
    - deploy/task.hcl

environments:
  staging:
    domain: staging.musee.sacha.house
    noIndex: true
  production:
    domain: musee.sacha.house

resources:
  cpu: 200
  memory: 128
